############################################################################################
#                                                                                          #
#                          _____     _           _   _       _                             #
#                         / ____|   | |         | | (_)     | |                            #
#                        | |     ___| | ___  ___| |_ _  __ _| |                            #
#                        | |    / _ \ |/ _ \/ __| __| |/ _` | |                            #
#                        | |___|  __/ |  __/\__ \ |_| | (_| | |                            #
#                         \_____\___|_|\___||___/\__|_|\__,_|_|                            #
#                                                                                          #
#    01000011 01100101 01101100 01100101 01110011 01110100 01101001 01100001 01101100      #
#                                                                                          #
############################################################################################
name: ${project.artifactId}
version: ${project.version}
main: ${project.main}
author: ${project.author}
description: ${project.description}